version: "3.8"
services:
  ## Apache Tika Server
  tika:
    user: 0:0
    stdin_open: true
    tty: true
    image: apache/tika:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:3355:9998"
    volumes:
      - storage:/var

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/storage
      o: bind
